# Generated by Django 3.0.7 on 2020-07-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='obstime',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
